# Generated by Django 2.2 on 2023-04-22 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noun_plural', models.CharField(max_length=200)),
                ('noun', models.CharField(max_length=200)),
                ('animal', models.CharField(max_length=200)),
                ('verb_base_form', models.CharField(max_length=200)),
                ('noun_2', models.CharField(max_length=200)),
                ('animal_2', models.CharField(max_length=200)),
                ('verb_base_form_2', models.CharField(max_length=200)),
                ('noun_plural_2', models.CharField(max_length=200)),
                ('verb_base_form_3', models.CharField(max_length=200)),
                ('noun_3', models.CharField(max_length=200)),
                ('noun_4', models.CharField(max_length=200)),
            ],
        ),
    ]
