# Generated by Django 2.2 on 2023-04-22 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('madLIbs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='animal_2',
            new_name='adjective',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='noun_plural_2',
        ),
    ]
