# Generated by Django 2.2 on 2023-04-22 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('madLIbs', '0002_auto_20230422_0259'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='verb_base_form_3',
        ),
    ]
