# Generated by Django 2.2 on 2023-04-22 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('madLIbs', '0003_remove_profile_verb_base_form_3'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='story_type',
            field=models.CharField(default='story1', max_length=200),
        ),
    ]
